Remove leading whitespace from xtask input curl config
With curl-8.13.0-rc2 the whitespace causes

    error: curl exited with code exit status: 26: curl: <stdin>:4: '' is unknown
    curl: cannot read config from '-'
    curl: option --config: error encountered when reading a file
    curl: try 'curl --help' or 'curl --manual' for more information

Bisected to https://github.com/curl/curl/commit/a7fda9a8f47aa7400c2eb2497b0ecf6687eace25